### ISSUE TITLE
permission issue with runtime compilation of vcontacs.so

### ISSUE THREAD

**Issue by aozalevsky** [gregorpatof/nrgten_package#2]
Due to the hack introduced in https://github.com/gregorpatof/nrgten_package/blob/aa56f139d788e673bb64f83fa48030f72ce942f1/src/nrgten/vcontacts_wrapper.py#L100-L120

The actual compilation is called during runtime:

https://github.com/gregorpatof/nrgten_package/blob/aa56f139d788e673bb64f83fa48030f72ce942f1/src/nrgten/vcontacts_wrapper.py#L62

So if the library was installed systemwide, the user won't have enough permission to compile the lib and will get quite puzzling error:
```
ValueError: This is libnames: []
and this is libpath: /usr/local/lib/python3.8/dist-packages/nrgten/vcontacts
```

I would rather recommend avoiding the hack and use the standard extension routine or explicitly mention the issue in the installation manual. Hope this would help.

**Comment by gregorpatof** [comment]
Hi,

Sorry for the late reply. The compilation has been moved to the pyvcon package which encapsulates the C executable. It is legacy code with many global variables and all our efforts to integrate it better have led to bugs. However, the error message one gets is now much clearer : "There was a problem with the automatic compilation of Vcontacts. See the Troubleshooting section of the NRGTEN online documentation (nrgten.readthedocs.io)". The doc now explains the issue.
